name: chat_app_client
description: A simple chat application that sends messages and receives messages from a server.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.0-144.0.dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  socket_io_client: ^1.0.2
  provider: ^6.0.2
  animated_text_kit: ^4.2.1
  google_fonts: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
